# Generated by Django 3.1.7 on 2021-03-26 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(10)])),
            ],
        ),
    ]
